import fs from "node:fs"
import path from "node:path"
// @ts-ignore
import solc from "solc"
import { createWalletClient, createPublicClient, http, defineChain } from "viem"
import { privateKeyToAccount } from "viem/accounts"

const xLayerTestnet = defineChain({
  id: 1952,
  name: "X Layer Testnet",
  nativeCurrency: { name: "OKB", symbol: "OKB", decimals: 18 },
  rpcUrls: {
    default: { http: ["https://testrpc.xlayer.tech/terigon"] },
  },
  blockExplorers: {
    default: { name: "OKX Explorer", url: "https://www.okx.com/web3/explorer/xlayer-test" },
  },
})

export function compileRouterContract() {
  const contractPath = path.resolve(process.cwd(), "contracts/XecuteTestnetRouter.sol")
  const source = fs.readFileSync(contractPath, "utf8")

  const input = {
    language: "Solidity",
    sources: {
      "XecuteTestnetRouter.sol": {
        content: source,
      },
    },
    settings: {
      outputSelection: {
        "*": {
          "*": ["abi", "evm.bytecode"],
        },
      },
      optimizer: {
        enabled: true,
        runs: 200,
      },
    },
  }

  const output = JSON.parse(solc.compile(JSON.stringify(input)))

  if (output.errors) {
    const fatal = output.errors.filter((e: { severity: string }) => e.severity === "error")
    if (fatal.length > 0) {
      console.error("Compilation errors:", fatal)
      throw new Error("Compilation failed")
    }
  }

  const contract = output.contracts["XecuteTestnetRouter.sol"]["XecuteTestnetRouter"]
  const abi = contract.abi
  const bytecode = `0x${contract.evm.bytecode.object}`

  const artifactsDir = path.resolve(process.cwd(), "src/lib/contracts")
  if (!fs.existsSync(artifactsDir)) {
    fs.mkdirSync(artifactsDir, { recursive: true })
  }

  const routerTsPath = path.join(artifactsDir, "router.ts")
  const routerTsContent = `// Auto-generated by scripts/deploy-testnet-router.ts
export const ROUTER_ADDRESS_TESTNET = "0x8888888888888888888888888888888888888888" as const

export const XECUTE_ROUTER_ABI = ${JSON.stringify(abi, null, 2)} as const

export const XECUTE_ROUTER_BYTECODE = "${bytecode}" as const
`

  fs.writeFileSync(routerTsPath, routerTsContent, "utf8")
  console.log("Compiled XecuteTestnetRouter.sol successfully. Saved ABI to src/lib/contracts/router.ts")
  return { abi, bytecode }
}

async function main() {
  const { abi, bytecode } = compileRouterContract()
  console.log("ABI Functions:", abi.filter((x: { type: string }) => x.type === "function").map((x: { name: string }) => x.name))

  const envLocalPath = path.resolve(process.cwd(), ".env.local")
  if (fs.existsSync(envLocalPath)) {
    try {
      // @ts-ignore
      if (typeof process.loadEnvFile === "function") {
        // @ts-ignore
        process.loadEnvFile(envLocalPath)
      } else {
        const envContent = fs.readFileSync(envLocalPath, "utf8")
        for (const line of envContent.split("\n")) {
          const match = line.match(/^\s*([\w_]+)\s*=\s*(.*)?\s*$/)
          if (match) {
            const key = match[1]
            let val = match[2] || ""
            if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
              val = val.slice(1, -1)
            }
            process.env[key] = val
          }
        }
      }
    } catch {}
  }

  let deployerKey = process.env.DEPLOYER_PRIVATE_KEY?.trim()
  if (deployerKey && !deployerKey.startsWith("0x")) {
    deployerKey = `0x${deployerKey}`
  }

  if (deployerKey && deployerKey.startsWith("0x") && deployerKey.length === 66) {
    const account = privateKeyToAccount(deployerKey as `0x${string}`)
    const publicClient = createPublicClient({
      chain: xLayerTestnet,
      transport: http("https://testrpc.xlayer.tech/terigon"),
    })
    const walletClient = createWalletClient({
      account,
      chain: xLayerTestnet,
      transport: http("https://testrpc.xlayer.tech/terigon"),
    })

    console.log(`Deploying from account: ${account.address} on X Layer Testnet (Chain ID 1952)...`)
    const gasPrice = await publicClient.getGasPrice().catch(() => BigInt(100000000))
    console.log(`Current gas price: ${gasPrice} wei`)

    const hash = await walletClient.deployContract({
      abi,
      bytecode: bytecode as `0x${string}`,
      gas: BigInt(2500000),
      gasPrice: gasPrice > BigInt(0) ? gasPrice : BigInt(100000000),
    })
    console.log(`Deployment TX broadcasted: ${hash}`)
    console.log(`Waiting for receipt...`)
    const receipt = await publicClient.waitForTransactionReceipt({ hash, timeout: 30000 })
    const deployedAddress = receipt.contractAddress
    console.log(`Contract deployed at: ${deployedAddress}`)
    console.log(`Explorer: https://www.okx.com/web3/explorer/xlayer-test/address/${deployedAddress}`)

    // Update src/lib/contracts/router.ts with deployed address
    const routerTsPath = path.resolve(process.cwd(), "src/lib/contracts/router.ts")
    if (fs.existsSync(routerTsPath) && deployedAddress) {
      let content = fs.readFileSync(routerTsPath, "utf8")
      content = content.replace(
        /export const ROUTER_ADDRESS_TESTNET = "[^"]+" as `0x\${string}`/,
        `export const ROUTER_ADDRESS_TESTNET = "${deployedAddress}" as \`0x\${string}\``,
      )
      fs.writeFileSync(routerTsPath, content, "utf8")
      console.log(`Updated src/lib/contracts/router.ts with ROUTER_ADDRESS_TESTNET = "${deployedAddress}"`)
    }
  } else {
    console.log("No valid DEPLOYER_PRIVATE_KEY found in environment or .env.local. Router ABI and Bytecode generated for client-side execution.")
  }
}

if (process.argv[1] === import.meta.filename) {
  void main()
}
